### PR TITLE
Add ability to change ST parameters

### PR DESCRIPTION
**Pull request by adamdossa**

### CODE REVIEW

**Comment by sangheraio** [comment]
Why do we need this?

**Review by satyamakgec — COMMENTED** [review]
As per the ICO standards these parameters -  decimals, name, total supply are not changeable

**Comment by adamdossa** [comment]
Hi @satyamakgec - could you point me at the docs for this standard? They are locked down as soon as the offering starts, which I think is OK.

**Comment by satyamakgec** [comment]
@adamdossa there are no docs for standard but as zeppelin-solidity did it make them hard-coded or passed in constructors there is no functionality to change those parameters so why we need to change them and I think issuers first have to strong as rock on their decision about the name, decimals, and total supply if they want to change it then launch a new one that makes them more careful to take every step in the direction of creating the issuing ST.  It is my opinion

**Comment by adamdossa** [comment]
So the thinking is that we want Issuers to create STs as soon as possible, and if they can't change these variables that may stop them from doing so. I can't see any reason to not allow these variables to change (up until the offering starts).

@pabloruiz55 @Everhusk

**Comment by adamdossa** [comment]
Just to add - given we are asking issuers to pay the paywall fee as part of the token creation, we want to put as little friction / decision making as possible before this step. Being able to change these basic parameters doesn't cause any problems and means that we can advise issuers that they have the option to change them at a later date (so not being 100% sure about them now should not prevent them creating the token).

**Review by sangheraio — APPROVED** [review]

**Pull request merged**
